# This file is only used to run backend and frontend locally.
# For production deployment in cloud, please refer to docker-compose.yaml. 

services:
  database:
    image: postgres:16.4
    restart: always
    volumes:
      - backend-db-data:/var/lib/postgresql/data
      - ./db-migrations/1.sql:/docker-entrypoint-initdb.d/1.sql
    env_file:
      - .env
    ports:
      - 5432:5432
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    depends_on:
      - database
    ports:
      - 9000:8080

volumes:
  backend-db-data:
